# Generated by Django 5.2.5 on 2025-09-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100, null=True)),
                ('lastName', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=1000)),
                ('countryCode', models.IntegerField(default=243)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('confirmationCode', models.IntegerField(null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('provider', 'Pr'), ('customer', 'Cs')])),
            ],
        ),
    ]
