# Generated by Django 5.2.5 on 2025-09-05 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_alter_category_name_alter_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
