# Generated by Django 5.2.5 on 2025-09-08 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('pricingFrequency', models.CharField(choices=[('hour', 'H'), ('day', 'D'), ('month', 'M')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000000000, null=True)),
                ('currency', models.CharField(choices=[('Dollar', 'Usd'), ('Franc Congolais', 'Cdf')])),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='public.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.user')),
            ],
        ),
    ]
