# Generated by Django 5.2.5 on 2025-09-13 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_alter_equipment_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DecimalField(decimal_places=1, max_digits=100, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('state', models.CharField(default='created', null=True)),
                ('paymentMethod', models.CharField(default='mobileMoney')),
                ('numberPhone', models.CharField(null=True)),
                ('rentStart', models.DateTimeField(null=True)),
                ('rentEnd', models.DateTimeField(null=True)),
                ('receiptCode', models.CharField(null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='public.user')),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='public.equipment')),
            ],
        ),
    ]
