# Generated by Django 5.2.5 on 2025-09-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0009_alter_equipment_price_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.FileField(null=True, upload_to='equipments/'),
        ),
    ]
