# Generated by Django 5.2.5 on 2025-11-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0010_equipment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='companyName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
