# Generated by Django 5.2.5 on 2025-11-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0011_user_companyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.CharField(null=True),
        ),
    ]
