# Generated by Django 5.2.5 on 2025-11-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0012_equipment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='location',
            field=models.CharField(null=True),
        ),
    ]
