# Generated by Django 5.2.5 on 2025-11-18 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0013_equipment_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='Category',
            new_name='category',
        ),
    ]
