# Generated by Django 5.2.5 on 2025-11-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0014_rename_category_equipment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logo',
            field=models.FileField(null=True, upload_to='providers/'),
        ),
        migrations.AddField(
            model_name='user',
            name='summary',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
