# Generated by Django 5.2.5 on 2025-11-20 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100, null=True)),
                ('lastName', models.CharField(max_length=100, null=True)),
                ('companyName', models.CharField(max_length=100, null=True)),
                ('summary', models.CharField(max_length=100, null=True)),
                ('logo', models.FileField(null=True, upload_to='providers/')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=1000)),
                ('countryCode', models.IntegerField(default=243)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('confirmationCode', models.IntegerField(null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('provider', 'Pr'), ('customer', 'Cs')])),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='public.category')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.CharField(null=True)),
                ('location', models.CharField(null=True)),
                ('pricingFrequency', models.CharField(choices=[('hour', 'H'), ('day', 'D'), ('month', 'M')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('currency', models.CharField(choices=[('Dollar', 'Usd'), ('Franc Congolais', 'Cdf')])),
                ('image', models.FileField(null=True, upload_to='equipments/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='public.category')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='public.user')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DecimalField(decimal_places=1, max_digits=100, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('state', models.CharField(default='created', null=True)),
                ('paymentMethod', models.CharField(default='mobileMoney')),
                ('numberPhone', models.CharField(null=True)),
                ('rentStart', models.DateTimeField(null=True)),
                ('rentEnd', models.DateTimeField(null=True)),
                ('receiptCode', models.CharField(null=True)),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='public.equipment')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='public.user')),
            ],
        ),
    ]
