# Generated by Django 5.2.5 on 2025-11-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='mobileMoneyPhone',
            field=models.CharField(null=True),
        ),
    ]
