# Generated by Django 5.2.5 on 2025-11-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_rent_mobilemoneyphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='createdAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
