# Generated by Django 5.2.5 on 2025-11-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_equipment_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='createdAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('provider', 'Pr'), ('customer', 'Cs')], null=True),
        ),
    ]
