# Generated by Django 5.2.5 on 2025-11-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_customuser_confirmedat_customuser_createdat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='createdAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
