# Generated by Django 5.2.5 on 2025-11-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_rent_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='rentTotalAmount',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
    ]
