# Generated by Django 5.2.5 on 2026-03-17 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0009_rent_renttotalamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('provider', 'Fournisseur'), ('customer', 'Client')], null=True),
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='created', null=True)),
                ('withdrawMethod', models.CharField(default='mobileMoney')),
                ('mobileMoneyPhone', models.CharField(null=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('confirmedAt', models.DateTimeField(null=True)),
                ('transactionCode', models.CharField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('currency', models.CharField(default='usd', null=True)),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='public.user')),
            ],
        ),
    ]
