# Generated by Django 5.2.5 on 2026-03-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0011_alter_rent_customer_alter_withdraw_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='currency',
            field=models.CharField(default='usd', null=True),
        ),
    ]
