# Generated by Django 5.2.5 on 2026-03-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0012_rent_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='paymentId',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='paymentToken',
            field=models.CharField(null=True),
        ),
    ]
